# Generated by Django 5.1.6 on 2025-02-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquareCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_number', models.PositiveIntegerField(unique=True)),
                ('output_number', models.IntegerField()),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripletCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_number_a', models.IntegerField()),
                ('input_number_b', models.IntegerField()),
                ('input_number_c', models.IntegerField()),
                ('is_pythagorean', models.BooleanField()),
                ('product', models.IntegerField()),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('input_number_a', 'input_number_b', 'input_number_c')},
            },
        ),
    ]
